_target_: src.methods.MTopDiv
zero_out: prompt
analysis_sites: all 
mode: unsupervised
model_name: ${model_name}
dtype: float16
device: cuda
cache_dir: cache/mtopdiv
normalize_by_length: True
n_jobs: 4
critical_size: 256
n_layers: 32
n_heads: 32
n_max: 6