_target_: src.methods.SemanticEntropy
model_name: ${model_name} 
dtype: float16 
device: cuda
cache_dir: cache/semantic_entropy
generated_responses_dir: cache/generated_responses
num_return_sequences: 20
temperature: 1.0
max_new_tokens: 256
