defaults:
  - method: mtopdiv
  - preprocess: coqa
  - transfer: coqa
  - evaluation: default
  - _self_


model_name: Mistral-7B-Instruct-v0.1 # Llama-3.1-8B-Instruct # Llama-2-7b-chat-hf # Llama-3.1-8B-Instruct # Meta-Llama-3-8B-Instruct
transfer_names: ["squad", "xsum"]
